spring:
  application:
    name: event
  web.mvc.servlet.path: /${spring.application.name} # Match With The Springboot Application Name
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5430/event-db
    username: app
    password: secret
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/patungan-ku
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /event/v3/api-docs/swagger-config
    urls:
      - name: API - V1
        url: /event/v3/api-docs/API - V1
    urls-primary-name: API - V1

logging:
  level:
    '[id.patunganku.event_service]': DEBUG